export const herbCodes = [
    { code: '0001_bac_ha', name: 'Bạc hà', source: 'https://medlatec.vn' },
    { code: '0002_bach_bo', name: 'Bách bộ', source: 'https://vinmec.com' },
    { code: '0003_bach_dong_nu', name: 'Bạch đồng nữ', source: 'https://suckhoedoisong.vn' },
    { code: '0004_bach_hoa_xa_thiet_thao', name: 'Bạch hoa xà thiệt thảo', source: 'https://nhathuoclongchau.com.vn' },
    { code: '0005_ban_ha_nam', name: 'Ban ha nam', source: 'https://medlatec.vn' },
    { code: '0006_bo_chinh_sam', name: 'Bo chinh sam' },
    { code: '0007_bo_cong_anh', name: 'Bo cong anh' },
    { code: '0008_ca_gai_leo', name: 'Ca gai leo' },
    { code: '0009_cam_thao_dat', name: 'Cam thao dat' },
    { code: '0010_co_man_trau', name: 'Co man trau' },
    { code: '0011_co_nho_noi', name: 'Co nho noi' },
    { code: '0012_co_sua_la_nho', name: 'Co sua la nho' },
    { code: '0013_co_tranh', name: 'Co tranh' },
    { code: '0014_co_xuoc', name: 'Co xuoc' },
    { code: '0015_coi_xay', name: 'Coi xay' },
    { code: '0016_cot_khi', name: 'Cot khi' },
    { code: '0017_cuc_hoa', name: 'Cuc hoa' },
    { code: '0018_cuc_tan_tu_bi', name: 'Cuc tan tu bi' },
    { code: '0019_danh_danh', name: 'Danh danh' },
    { code: '0020_dau', name: 'Dau' },
  ];